size(400,400);

colorMode(HSB,100);
background(100);

final float SUURI_SIVU=300;
final float PIENI_SIVU=100;

final float SUURI_SAVY=50;
final float SAVY_MUUTOS=20;
final float KYLLAISUUS=90;
final float KIRKKAUS= 95;

fill(SUURI_SAVY,KYLLAISUUS,KIRKKAUS);
rect(0,0,SUURI_SIVU,SUURI_SIVU);

fill(SUURI_SAVY+SAVY_MUUTOS,KYLLAISUUS,KIRKKAUS);
rect(0,0,PIENI_SIVU,PIENI_SIVU);

fill(SUURI_SAVY+2*SAVY_MUUTOS,KYLLAISUUS,KIRKKAUS);
rect(SUURI_SIVU-PIENI_SIVU,SUURI_SIVU-PIENI_SIVU,PIENI_SIVU,PIENI_SIVU);
